name: Metrics Part 2
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics-part2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: metadata
          config_timezone: Europe/Istanbul
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          filename: /metrics_renders/github-metrics-2.svg
